CREATE TABLE `address` (
  `ADDRESS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DONOR_ID` bigint(20) DEFAULT NULL,
  `LINE1` varchar(100) NOT NULL,
  `LINE2` varchar(100) DEFAULT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(25) NOT NULL,
  `ZIPCODE` varchar(10) NOT NULL,
  `MAJOR_INTERSECTION` varchar(45) NOT NULL,
  `SUBDIVISION` varchar(45) DEFAULT NULL,
  `STREET_SUFFIX` varchar(20) DEFAULT NULL,
  `STRUCTURE_TYPE` varchar(45) DEFAULT NULL,
  `UNIT` varchar(10) DEFAULT NULL,
  `BUILDING` varchar(10) DEFAULT NULL,
  `FLOOR` varchar(3) DEFAULT NULL,
  `ELEVATOR_FLAG` varchar(3) DEFAULT 'No',
  `GATED_FLAG` varchar(3) DEFAULT 'No',
  `GATE_INSTRUCTIONS` varchar(60) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=136228 DEFAULT CHARSET=utf8;

CREATE TABLE `call_log` (
  `CALL_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CALL_TYPE` varchar(45) NOT NULL,
  `SOURCE` varchar(60) NOT NULL,
  `CALL_DATE` varchar(45) NOT NULL,
  `CALL_AGENT` varchar(25) NOT NULL,
  `FARM_BASE` varchar(45) NOT NULL,
  PRIMARY KEY (`CALL_LOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=27627 DEFAULT CHARSET=utf8;

CREATE TABLE `course` (
  `COURSE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(25) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `BEGIN_DATE` varchar(10) DEFAULT NULL,
  `END_DATE` varchar(10) DEFAULT NULL,
  `BEGIN_TIME` varchar(10) DEFAULT NULL,
  `END_TIME` varchar(10) DEFAULT NULL,
  `MEETING_DAYS` varchar(7) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`COURSE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `course_instructor` (
  `COURSE_INSTRUCTOR_ID` bigint(20) NOT NULL,
  `COURSE_ID` bigint(20) NOT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`COURSE_INSTRUCTOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `course_rotation_history` (
  `COURSE_ROTATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROTATION_DATE` varchar(45) DEFAULT NULL,
  `MOVED_COURSE_0_TO_1` int(11) DEFAULT NULL,
  `MOVED_COURSE_1_TO_2` int(11) DEFAULT NULL,
  `MOVED_COURSE_2_TO_3` int(11) DEFAULT NULL,
  `MOVED_COURSE_3_TO_4` int(11) DEFAULT NULL,
  `MOVED_COURSE_4_TO_5` int(11) DEFAULT NULL,
  `MOVED_COURSE_5_TO_6` int(11) DEFAULT NULL,
  `HELD_COURSE_0` int(11) DEFAULT NULL,
  `HELD_COURSE_1` int(11) DEFAULT NULL,
  `HELD_COURSE_2` int(11) DEFAULT NULL,
  `HELD_COURSE_3` int(11) DEFAULT NULL,
  `HELD_COURSE_4` int(11) DEFAULT NULL,
  `HELD_COURSE_5` int(11) DEFAULT NULL,
  `HELD_COURSE_6` int(11) DEFAULT NULL,
  `GRADUATED` int(11) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `FARM_BASE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`COURSE_ROTATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_certification_student_exam` (
  `certification_exam_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `program_id` bigint(20) NOT NULL,
  `exam_date` varchar(20) DEFAULT NULL,
  `grade` varchar(10) DEFAULT NULL,
  `intake_id` bigint(20) NOT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`certification_exam_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_department` (
  `department_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `farm_base` varchar(45) DEFAULT NULL,
  `creation_date` varchar(45) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `title` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`department_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_job` (
  `job_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `creation_date` varchar(45) DEFAULT NULL,
  `department_id` bigint(20) NOT NULL,
  PRIMARY KEY (`job_id`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_job_assignment` (
  `JOB_ASSIGNMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `intake_id` bigint(20) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `job_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`JOB_ASSIGNMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='	';

CREATE TABLE `cwt_job_metric` (
  `metric_id` bigint(20) DEFAULT NULL,
  `job_id` bigint(20) DEFAULT NULL,
  `metric_job_id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`metric_job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_metrics` (
  `metric_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `metric_name` varchar(250) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`metric_id`)
) ENGINE=InnoDB AUTO_INCREMENT=216 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_module_section` (
  `module_offering_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `module_id` bigint(20) DEFAULT NULL,
  `meeting_days` varchar(10) DEFAULT NULL,
  `meeting_times` varchar(10) DEFAULT NULL,
  `credit_hours` varchar(3) DEFAULT NULL,
  `instructor_id` bigint(20) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `effective_date` varchar(20) DEFAULT NULL,
  `expiration_date` varchar(20) DEFAULT NULL,
  `location` varchar(60) DEFAULT NULL,
  `farm_base` varchar(50) DEFAULT NULL,
  `instructor_notes` longtext CHARACTER SET latin1,
  `administrator_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`module_offering_id`)
) ENGINE=InnoDB AUTO_INCREMENT=681 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_module_student` (
  `module_roster_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `module_offering_id` bigint(20) DEFAULT NULL,
  `intake_id` bigint(20) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `meeting_date` varchar(20) DEFAULT NULL,
  `completion_flag` varchar(20) DEFAULT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`module_roster_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_modules` (
  `module_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `module_name` varchar(50) DEFAULT NULL,
  `description` longtext,
  `status` varchar(10) DEFAULT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  `meeting_days` varchar(45) DEFAULT NULL,
  `meeting_times` varchar(45) DEFAULT NULL,
  `instructor_id` bigint(20) DEFAULT NULL,
  `meeting_location` varchar(45) DEFAULT NULL,
  `program_id` bigint(20) DEFAULT NULL,
  `module_sequence` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`module_id`)
) ENGINE=InnoDB AUTO_INCREMENT=930 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_program` (
  `program_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `program_name` varchar(50) DEFAULT NULL,
  `description` varchar(150) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  `created_by` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`program_id`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_program_metric` (
  `program_metric_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `metric_id` bigint(20) DEFAULT NULL,
  `program_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`program_metric_id`)
) ENGINE=InnoDB AUTO_INCREMENT=317 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_program_metric_modules` (
  `metric_id` bigint(20) NOT NULL,
  `module_id` bigint(20) NOT NULL,
  `status` varchar(15) DEFAULT NULL,
  `program_metric_module_id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`program_metric_module_id`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_roster` (
  `roster_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `module_id` bigint(20) NOT NULL,
  `section_id` bigint(20) NOT NULL,
  `intake_id` bigint(20) NOT NULL,
  `attend_flag` varchar(15) DEFAULT NULL,
  `exam_score` varchar(5) DEFAULT NULL,
  `last_updated_by` varchar(20) DEFAULT NULL,
  `last_updated_date` varchar(20) DEFAULT NULL,
  `attend_date` varchar(20) DEFAULT NULL,
  `exam_date` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `job_id` bigint(20) DEFAULT NULL,
  `department_id` bigint(20) DEFAULT NULL,
  `supervisor_id` bigint(20) DEFAULT NULL,
  `archived_flag` varchar(20) DEFAULT NULL,
  `roster_date` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`roster_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3787 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_roster_notes` (
  `notes_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `section_id` bigint(20) DEFAULT NULL,
  `roster_date` varchar(20) DEFAULT NULL,
  `notes` longblob,
  PRIMARY KEY (`notes_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `cwt_supervisor` (
  `supervisor_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `firstname` varchar(45) DEFAULT NULL,
  `lastname` varchar(45) DEFAULT NULL,
  `job_id` bigint(20) DEFAULT NULL,
  `creation_date` varchar(45) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `department_id` bigint(20) DEFAULT NULL,
  `farm_base` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`supervisor_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10059 DEFAULT CHARSET=utf8;

CREATE TABLE `daily_limit` (
  `DAILY_LIMIT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DISPATCH_DATE` varchar(45) NOT NULL,
  `DAILY_LIMIT` int(11) NOT NULL DEFAULT '65',
  `UPDATED_BY` varchar(45) NOT NULL,
  `UPDATED_DATE` varchar(25) NOT NULL,
  `FARM_BASE` varchar(45) NOT NULL,
  `SPECIAL_LIMIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`DAILY_LIMIT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=994 DEFAULT CHARSET=utf8;

CREATE TABLE `donation` (
  `DONATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DONOR_ID` bigint(20) NOT NULL,
  `CONFIRMATION_NUMBER` varchar(45) DEFAULT NULL,
  `DISPATCH_DATE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `SPECIAL_FLAG` varchar(45) DEFAULT 'No',
  `CALL_REQUIREMENTS` varchar(45) DEFAULT NULL,
  `AC` varchar(45) DEFAULT NULL,
  `BEDDING` varchar(45) DEFAULT NULL,
  `BEDDING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `BOOKS` varchar(45) DEFAULT NULL,
  `BOOKS_QTY_TYPE` varchar(45) DEFAULT NULL,
  `CLOTHING` varchar(45) DEFAULT NULL,
  `CLOTHING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `COMPUTER` varchar(45) DEFAULT NULL,
  `DESK` varchar(45) DEFAULT NULL,
  `CHEST` varchar(45) DEFAULT NULL,
  `ARMOIRE` varchar(45) DEFAULT NULL,
  `DRESSER` varchar(45) DEFAULT NULL,
  `MIRROR` varchar(45) DEFAULT NULL,
  `NIGHTSTAND` varchar(45) DEFAULT NULL,
  `HEADBOARD` varchar(45) DEFAULT NULL,
  `FOOTBOARD` varchar(45) DEFAULT NULL,
  `RAILS` varchar(45) DEFAULT NULL,
  `LAMP` varchar(45) DEFAULT NULL,
  `LAWN_FURNITURE` varchar(45) DEFAULT NULL,
  `MATTRESS` varchar(45) DEFAULT NULL,
  `MATTRESS_QTY_SIZE` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEMS` varchar(45) DEFAULT NULL,
  `REFRIDGERATOR` varchar(45) DEFAULT NULL,
  `STOVE` varchar(45) DEFAULT NULL,
  `RECLINER` varchar(45) DEFAULT NULL,
  `SOFA` varchar(45) DEFAULT NULL,
  `LOVESEAT` varchar(45) DEFAULT NULL,
  `WALL_UNIT` varchar(45) DEFAULT NULL,
  `TABLES` varchar(45) DEFAULT NULL,
  `CHAIR` varchar(45) DEFAULT NULL,
  `TELEVISION` varchar(45) DEFAULT NULL,
  `TELEVISION_SIZE` varchar(45) DEFAULT NULL,
  `ELECTRONICS` varchar(45) DEFAULT NULL,
  `WASHER` varchar(45) DEFAULT NULL,
  `DRYER` varchar(45) DEFAULT NULL,
  `EXERCISE_EQUIPMENT` varchar(45) DEFAULT NULL,
  `SPECIAL_NOTES` mediumtext,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `FARM_BASE` varchar(45) NOT NULL,
  `TABLE_TYPE` varchar(45) DEFAULT NULL,
  `CHAIR_TYPE` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `BOOKCASE` varchar(45) DEFAULT NULL,
  `OTTOMAN` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEM_QTY_SIZE` varchar(45) DEFAULT NULL,
  `WALL_UNIT_QTY_SIZE` varchar(45) DEFAULT NULL,
  `GATE_CODE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`DONATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=102763 DEFAULT CHARSET=utf8;

CREATE TABLE `donation_ticket` (
  `DONATION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LASTNAME` varchar(45) DEFAULT NULL,
  `FIRSTNAME` varchar(45) DEFAULT NULL,
  `SUFFIX` varchar(45) DEFAULT NULL,
  `CONTACT_PHONE` varchar(45) DEFAULT NULL,
  `PHONE_OTHER` varchar(45) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(45) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(200) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(200) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `ZIPCODE` varchar(45) DEFAULT NULL,
  `MAJOR_INTERSECTION` varchar(45) DEFAULT NULL,
  `SUBDIVISION` varchar(45) DEFAULT NULL,
  `STREET_SUFFIX` varchar(45) DEFAULT NULL,
  `STRUCTURE_TYPE` varchar(45) DEFAULT NULL,
  `UNIT` varchar(45) DEFAULT NULL,
  `BUILDING` varchar(45) DEFAULT NULL,
  `FLOOR` varchar(45) DEFAULT NULL,
  `ELEVATOR_FLAG` varchar(45) DEFAULT NULL,
  `GATED_FLAG` varchar(45) DEFAULT NULL,
  `GATE_INSTRUCTIONS` varchar(45) DEFAULT NULL,
  `DISPATCH_DATE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `SPECIAL_FLAG` varchar(45) DEFAULT 'No',
  `CALL_REQUIREMENTS` varchar(45) DEFAULT NULL,
  `AC` varchar(45) DEFAULT NULL,
  `BEDDING` varchar(45) DEFAULT NULL,
  `BEDDING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `BOOKS` varchar(45) DEFAULT NULL,
  `BOOKS_QTY_TYPE` varchar(45) DEFAULT NULL,
  `CLOTHING` varchar(45) DEFAULT NULL,
  `CLOTHING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `COMPUTER` varchar(45) DEFAULT NULL,
  `DESK` varchar(45) DEFAULT NULL,
  `CHEST` varchar(45) DEFAULT NULL,
  `ARMOIRE` varchar(45) DEFAULT NULL,
  `DRESSER` varchar(45) DEFAULT NULL,
  `MIRROR` varchar(45) DEFAULT NULL,
  `NIGHTSTAND` varchar(45) DEFAULT NULL,
  `HEADBOARD` varchar(45) DEFAULT NULL,
  `FOOTBOARD` varchar(45) DEFAULT NULL,
  `RAILS` varchar(45) DEFAULT NULL,
  `LAMP` varchar(45) DEFAULT NULL,
  `LAWN_FURNITURE` varchar(45) DEFAULT NULL,
  `MATTRESS` varchar(45) DEFAULT NULL,
  `MATTRESS_QTY_SIZE` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEMS` varchar(45) DEFAULT NULL,
  `REFRIDGERATOR` varchar(45) DEFAULT NULL,
  `STOVE` varchar(45) DEFAULT NULL,
  `RECLINER` varchar(45) DEFAULT NULL,
  `SOFA` varchar(45) DEFAULT NULL,
  `LOVESEAT` varchar(45) DEFAULT NULL,
  `WALL_UNIT` varchar(45) DEFAULT NULL,
  `TABLES` varchar(45) DEFAULT NULL,
  `CHAIR` varchar(45) DEFAULT NULL,
  `TELEVISION` varchar(45) DEFAULT NULL,
  `TELEVISION_SIZE` varchar(45) DEFAULT NULL,
  `ELECTRONICS` varchar(45) DEFAULT NULL,
  `WASHER` varchar(45) DEFAULT NULL,
  `DRYER` varchar(45) DEFAULT NULL,
  `EXERCISE_EQUIPMENT` varchar(45) DEFAULT NULL,
  `SPECIAL_NOTES` mediumtext,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `FARM_BASE` varchar(45) NOT NULL,
  `TABLE_TYPE` varchar(45) DEFAULT NULL,
  `CHAIR_TYPE` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `BOOKCASE` varchar(45) DEFAULT NULL,
  `OTTOMAN` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEM_QTY_SIZE` varchar(45) DEFAULT NULL,
  `WALL_UNIT_QTY_SIZE` varchar(45) DEFAULT NULL,
  `GATE_CODE` varchar(20) DEFAULT NULL,
  `GOOGLE_CONF_NUMBER` bigint(40) DEFAULT NULL,
  PRIMARY KEY (`DONATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=190424 DEFAULT CHARSET=utf8;

CREATE TABLE `donor` (
  `DONOR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LASTNAME` varchar(40) NOT NULL,
  `FIRSTNAME` varchar(40) NOT NULL,
  `SUFFIX` varchar(4) DEFAULT NULL,
  `CONTACT_PHONE` varchar(13) NOT NULL,
  `EMAIL_ADDRESS` varchar(60) NOT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(40) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `PHONE_OTHER` varchar(13) DEFAULT NULL,
  PRIMARY KEY (`DONOR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4124064 DEFAULT CHARSET=utf8;

CREATE TABLE `google_address` (
  `addressType` varchar(50) DEFAULT NULL,
  `floorNumber` varchar(50) DEFAULT NULL,
  `zipcode` varchar(50) DEFAULT NULL,
  `addressLine2` varchar(150) DEFAULT NULL,
  `addressLine1` varchar(150) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `structureType` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `streetSuffix` varchar(50) DEFAULT NULL,
  `elevatorFlag` varchar(50) DEFAULT NULL,
  `majorIntersection` varchar(50) DEFAULT NULL,
  `personKey` int(11) DEFAULT NULL,
  `cellPhone` varchar(50) DEFAULT NULL,
  `gatedCommunity` varchar(50) DEFAULT NULL,
  `gateInstructions` varchar(50) DEFAULT NULL,
  `lastUpdatedBy` varchar(58) DEFAULT NULL,
  `createdBy` varchar(50) DEFAULT NULL,
  `workPhone` varchar(50) DEFAULT NULL,
  `creationDate` varchar(50) DEFAULT NULL,
  `homePhone` varchar(50) DEFAULT NULL,
  `building` varchar(50) DEFAULT NULL,
  `subdivision` varchar(50) DEFAULT NULL,
  `apartmentNumber` varchar(50) DEFAULT NULL,
  `email` varchar(56) DEFAULT NULL,
  `lastUpdatedDate` varchar(50) DEFAULT NULL,
  `buildingNumber` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `google_dispatch` (
  `televisionSize` varchar(50) DEFAULT NULL,
  `zipcode` varchar(50) DEFAULT NULL,
  `loveseat` varchar(50) DEFAULT NULL,
  `acceptEmailNotifications` varchar(50) DEFAULT NULL,
  `acceptTermsPolicies` varchar(50) DEFAULT NULL,
  `floorNumber` varchar(50) DEFAULT NULL,
  `updatedBy` varchar(58) DEFAULT NULL,
  `lawnFurniture` varchar(50) DEFAULT NULL,
  `nightstand` varchar(50) DEFAULT NULL,
  `creationBy` varchar(58) DEFAULT NULL,
  `computer` varchar(50) DEFAULT NULL,
  `books` varchar(50) DEFAULT NULL,
  `stove` varchar(50) DEFAULT NULL,
  `mirror` varchar(50) DEFAULT NULL,
  `miscBagsBoxes` varchar(50) DEFAULT NULL,
  `chair` varchar(50) DEFAULT NULL,
  `clothing` varchar(50) DEFAULT NULL,
  `gateCode` varchar(50) DEFAULT NULL,
  `gatedCommunityFlag` varchar(50) DEFAULT NULL,
  `clothingBagsBoxes` varchar(50) DEFAULT NULL,
  `structureType` varchar(54) DEFAULT NULL,
  `dispatchLocation` varchar(50) DEFAULT NULL,
  `callRequirements` varchar(50) DEFAULT NULL,
  `wallUnitPieces` varchar(50) DEFAULT NULL,
  `bedding` varchar(50) DEFAULT NULL,
  `lamp` varchar(50) DEFAULT NULL,
  `rails` varchar(50) DEFAULT NULL,
  `otherItems` varchar(50) DEFAULT NULL,
  `chest` varchar(50) DEFAULT NULL,
  `farmBase` varchar(50) DEFAULT NULL,
  `recliner` varchar(50) DEFAULT NULL,
  `vcr` varchar(50) DEFAULT NULL,
  `elevatorFlag` varchar(50) DEFAULT NULL,
  `majorIntersection` varchar(70) DEFAULT NULL,
  `dispatchType` varchar(50) DEFAULT NULL,
  `personKey` int(11) DEFAULT NULL,
  `dresser` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `gateInstructions` varchar(53) DEFAULT NULL,
  `exerciseEquipment` varchar(50) DEFAULT NULL,
  `entertainmentCenter` varchar(50) DEFAULT NULL,
  `footboard` varchar(50) DEFAULT NULL,
  `lastUpdated` varchar(50) DEFAULT NULL,
  `streetSuffix` varchar(50) DEFAULT NULL,
  `booksBagsBoxes` varchar(50) DEFAULT NULL,
  `dryer` varchar(50) DEFAULT NULL,
  `itemLocation` varchar(50) DEFAULT NULL,
  `lastUpdatedBy` varchar(61) DEFAULT NULL,
  `createdBy` varchar(58) DEFAULT NULL,
  `desk` varchar(50) DEFAULT NULL,
  `confirmationNumber` bigint(20) DEFAULT NULL,
  `creationDate` datetime DEFAULT NULL,
  `table` varchar(50) DEFAULT NULL,
  `washer` varchar(50) DEFAULT NULL,
  `refrigerator` varchar(50) DEFAULT NULL,
  `headboard` varchar(50) DEFAULT NULL,
  `airConditioner` varchar(50) DEFAULT NULL,
  `dispatchAddress` varchar(76) DEFAULT NULL,
  `television` varchar(50) DEFAULT NULL,
  `subdivision` varchar(55) DEFAULT NULL,
  `electronicEquipment` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `wallUnit` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `notes` varchar(507) DEFAULT NULL,
  `miscHouseholdItems` varchar(50) DEFAULT NULL,
  `middleInitial` varchar(50) DEFAULT NULL,
  `armoire` varchar(50) DEFAULT NULL,
  `unitNumber` varchar(50) DEFAULT NULL,
  `mattressSize` varchar(50) DEFAULT NULL,
  `beddingBagsBoxes` varchar(50) DEFAULT NULL,
  `truck` varchar(50) DEFAULT NULL,
  `lastUpdatedDate` varchar(50) DEFAULT NULL,
  `sofa` varchar(50) DEFAULT NULL,
  `mattressBoxSpring` varchar(50) DEFAULT NULL,
  `special` varchar(50) DEFAULT NULL,
  `buildingNumber` varchar(50) DEFAULT NULL,
  `dispatchDate` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `google_donation_ticket` (
  `DONATION_ID` bigint(40) NOT NULL AUTO_INCREMENT,
  `LASTNAME` varchar(45) DEFAULT NULL,
  `FIRSTNAME` varchar(45) DEFAULT NULL,
  `SUFFIX` varchar(45) DEFAULT NULL,
  `CONTACT_PHONE` varchar(45) DEFAULT NULL,
  `PHONE_OTHER` varchar(45) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(45) DEFAULT NULL,
  `ADDRESS_LINE1` varchar(80) DEFAULT NULL,
  `ADDRESS_LINE2` varchar(80) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `ZIPCODE` varchar(45) DEFAULT NULL,
  `MAJOR_INTERSECTION` varchar(45) DEFAULT NULL,
  `SUBDIVISION` varchar(45) DEFAULT NULL,
  `STREET_SUFFIX` varchar(45) DEFAULT NULL,
  `STRUCTURE_TYPE` varchar(45) DEFAULT NULL,
  `UNIT` varchar(45) DEFAULT NULL,
  `BUILDING` varchar(45) DEFAULT NULL,
  `FLOOR` varchar(45) DEFAULT NULL,
  `ELEVATOR_FLAG` varchar(45) DEFAULT NULL,
  `GATED_FLAG` varchar(45) DEFAULT NULL,
  `GATE_INSTRUCTIONS` varchar(45) DEFAULT NULL,
  `DISPATCH_DATE` varchar(45) DEFAULT NULL,
  `STATUS` varchar(45) DEFAULT NULL,
  `SPECIAL_FLAG` varchar(45) DEFAULT 'No',
  `CALL_REQUIREMENTS` varchar(45) DEFAULT NULL,
  `AC` varchar(45) DEFAULT NULL,
  `BEDDING` varchar(45) DEFAULT NULL,
  `BEDDING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `BOOKS` varchar(45) DEFAULT NULL,
  `BOOKS_QTY_TYPE` varchar(45) DEFAULT NULL,
  `CLOTHING` varchar(45) DEFAULT NULL,
  `CLOTHING_QTY_TYPE` varchar(45) DEFAULT NULL,
  `COMPUTER` varchar(45) DEFAULT NULL,
  `DESK` varchar(45) DEFAULT NULL,
  `CHEST` varchar(45) DEFAULT NULL,
  `ARMOIRE` varchar(45) DEFAULT NULL,
  `DRESSER` varchar(45) DEFAULT NULL,
  `MIRROR` varchar(45) DEFAULT NULL,
  `NIGHTSTAND` varchar(45) DEFAULT NULL,
  `HEADBOARD` varchar(45) DEFAULT NULL,
  `FOOTBOARD` varchar(45) DEFAULT NULL,
  `RAILS` varchar(45) DEFAULT NULL,
  `LAMP` varchar(45) DEFAULT NULL,
  `LAWN_FURNITURE` varchar(45) DEFAULT NULL,
  `MATTRESS` varchar(45) DEFAULT NULL,
  `MATTRESS_QTY_SIZE` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEMS` varchar(45) DEFAULT NULL,
  `REFRIDGERATOR` varchar(45) DEFAULT NULL,
  `STOVE` varchar(45) DEFAULT NULL,
  `RECLINER` varchar(45) DEFAULT NULL,
  `SOFA` varchar(45) DEFAULT NULL,
  `LOVESEAT` varchar(45) DEFAULT NULL,
  `WALL_UNIT` varchar(45) DEFAULT NULL,
  `TABLES` varchar(45) DEFAULT NULL,
  `CHAIR` varchar(45) DEFAULT NULL,
  `TELEVISION` varchar(45) DEFAULT NULL,
  `TELEVISION_SIZE` varchar(45) DEFAULT NULL,
  `ELECTRONICS` varchar(45) DEFAULT NULL,
  `WASHER` varchar(45) DEFAULT NULL,
  `DRYER` varchar(45) DEFAULT NULL,
  `EXERCISE_EQUIPMENT` varchar(45) DEFAULT NULL,
  `SPECIAL_NOTES` mediumtext,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `UPDATED_BY` varchar(45) DEFAULT NULL,
  `FARM_BASE` varchar(45) NOT NULL,
  `TABLE_TYPE` varchar(45) DEFAULT NULL,
  `CHAIR_TYPE` varchar(45) DEFAULT NULL,
  `LOCATION` varchar(45) DEFAULT NULL,
  `BOOKCASE` varchar(45) DEFAULT NULL,
  `OTTOMAN` varchar(45) DEFAULT NULL,
  `MISC_HOUSEHOLD_ITEM_QTY_SIZE` varchar(45) DEFAULT NULL,
  `WALL_UNIT_QTY_SIZE` varchar(45) DEFAULT NULL,
  `GATE_CODE` varchar(20) DEFAULT NULL,
  `GOOGLE_CONF_NUMBER` bigint(40) DEFAULT NULL,
  PRIMARY KEY (`DONATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=236797 DEFAULT CHARSET=utf8;

CREATE TABLE `google_person` (
  `lastPersonStatus` varchar(50) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `emergencyPhone` varchar(50) DEFAULT NULL,
  `exitDate` varchar(58) DEFAULT NULL,
  `englishReadFlag` varchar(50) DEFAULT NULL,
  `referredBy` varchar(50) DEFAULT NULL,
  `height` varchar(50) DEFAULT NULL,
  `englishSpeakFlag` varchar(50) DEFAULT NULL,
  `graduateFlag` varchar(50) DEFAULT NULL,
  `maritalStatus` varchar(50) DEFAULT NULL,
  `createdBy` varchar(54) DEFAULT NULL,
  `workAssignment` varchar(50) DEFAULT NULL,
  `personStatus` varchar(50) DEFAULT NULL,
  `entryDate` varchar(58) DEFAULT NULL,
  `bedNumber` varchar(50) DEFAULT NULL,
  `saved` varchar(50) DEFAULT NULL,
  `ethnicity` varchar(50) DEFAULT NULL,
  `currentCourse` varchar(50) DEFAULT NULL,
  `ssn` varchar(54) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `weight` varchar(50) DEFAULT NULL,
  `ytdPaid` varchar(50) DEFAULT NULL,
  `emergencyContact` varchar(50) DEFAULT NULL,
  `dateOfBirth` varchar(50) DEFAULT NULL,
  `lastStatusUpdated` varchar(58) DEFAULT NULL,
  `specialNotes` varchar(500) DEFAULT NULL,
  `supervisor` varchar(50) DEFAULT NULL,
  `homeLocation` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `cellPhone` varchar(50) DEFAULT NULL,
  `educationLevel` varchar(50) DEFAULT NULL,
  `referralPhone` varchar(50) DEFAULT NULL,
  `suffix` varchar(50) DEFAULT NULL,
  `eyeColor` varchar(50) DEFAULT NULL,
  `lastUpdatedBy` varchar(53) DEFAULT NULL,
  `legacyComment` varchar(500) DEFAULT NULL,
  `personKey` int(11) DEFAULT NULL,
  `bedAssignment` varchar(50) DEFAULT NULL,
  `hairColor` varchar(50) DEFAULT NULL,
  `workPhone` varchar(50) DEFAULT NULL,
  `creationDate` datetime DEFAULT NULL,
  `homePhone` varchar(50) DEFAULT NULL,
  `organization` varchar(50) DEFAULT NULL,
  `emergencyRelationship` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `age` varchar(50) DEFAULT NULL,
  `work` varchar(50) DEFAULT NULL,
  `middleInitial` varchar(50) DEFAULT NULL,
  `ssnCard` varchar(50) DEFAULT NULL,
  `personType` varchar(50) DEFAULT NULL,
  `farmBase` varchar(50) DEFAULT NULL,
  `imageKey` varchar(213) DEFAULT NULL,
  `lastUpdatedDate` varchar(50) DEFAULT NULL,
  `currentClass` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `intake` (
  `INTAKE_ID` bigint(11) NOT NULL AUTO_INCREMENT,
  `LASTNAME` varchar(30) DEFAULT NULL,
  `FIRSTNAME` varchar(30) DEFAULT NULL,
  `MI` varchar(5) DEFAULT NULL,
  `SUFFIX` varchar(5) DEFAULT NULL,
  `ADDRESS` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `STATE` varchar(25) DEFAULT NULL,
  `ZIPCODE` varchar(10) DEFAULT NULL,
  `DOB` varchar(40) DEFAULT NULL,
  `SSN` varchar(60) DEFAULT NULL,
  `SSN_CARD_FLAG` varchar(10) DEFAULT NULL,
  `AGE` varchar(10) DEFAULT NULL,
  `HEIGHT` varchar(20) DEFAULT NULL,
  `WEIGHT` varchar(10) DEFAULT NULL,
  `ETHNICITY` varchar(50) DEFAULT NULL,
  `HAIR_COLOR` varchar(40) DEFAULT NULL,
  `EYE_COLOR` varchar(20) DEFAULT NULL,
  `MARITAL_STATUS` varchar(30) DEFAULT NULL,
  `EDUCATION_LEVEL` varchar(25) DEFAULT NULL,
  `GRADUATE_FLAG` varchar(3) DEFAULT NULL,
  `TRANSCRIPTS_FLAG` varchar(3) DEFAULT NULL,
  `ENGLISH_SPEAKING_FLAG` varchar(3) DEFAULT NULL,
  `ENGLISH_READING_FLAG` varchar(3) DEFAULT NULL,
  `HOME_LOCATION` varchar(45) DEFAULT NULL,
  `REFERRED_BY` varchar(80) DEFAULT NULL,
  `REFERRED_BY_PHONE` varchar(45) DEFAULT NULL,
  `EMERGENCY_CONTACT` varchar(45) DEFAULT NULL,
  `EMERGENCY_PHONE` varchar(45) DEFAULT NULL,
  `EMERGENCRY_RELATIONSHIP` varchar(45) DEFAULT NULL,
  `MOTHER_LIVING_FLAG` varchar(3) DEFAULT NULL,
  `FATHER_LIVING_FLAG` varchar(3) DEFAULT NULL,
  `BROTHERS` varchar(5) DEFAULT NULL,
  `SISTERS` varchar(5) DEFAULT NULL,
  `CHILDREN` varchar(5) DEFAULT NULL,
  `VETERAN_STATUS` varchar(25) DEFAULT NULL,
  `BRANCH_OF_SERVICE` varchar(45) DEFAULT NULL,
  `RANK` varchar(45) DEFAULT NULL,
  `LENGTH_OF_SERVICE` varchar(45) DEFAULT NULL,
  `DL_FLAG` varchar(45) DEFAULT NULL,
  `DL_NUMBER` varchar(45) DEFAULT NULL,
  `DL_STATE` varchar(45) DEFAULT NULL,
  `DL_EXP_DATE` varchar(45) DEFAULT NULL,
  `STATE_ID_FLAG` varchar(3) DEFAULT NULL,
  `STATE_ID_STATE` varchar(45) DEFAULT NULL,
  `STATE_ID_EXP_DATE` varchar(45) DEFAULT NULL,
  `GOVERNMENT_BENEFITS_FLAG` varchar(60) DEFAULT NULL,
  `RELIGION` varchar(45) DEFAULT NULL,
  `RELIGIOUS_EXPERIENCE` mediumtext CHARACTER SET latin1,
  `ALCOHOL_LAST_USED` varchar(15) DEFAULT NULL,
  `COCAINE_LAST_USED` varchar(15) DEFAULT NULL,
  `MARIJUANA_LAST_USED` varchar(15) DEFAULT NULL,
  `OXYCODONE_LAST_USED` varchar(15) DEFAULT NULL,
  `SPEED_LAST_USED` varchar(15) DEFAULT NULL,
  `HEROIN_LAST_USED` varchar(15) DEFAULT NULL,
  `XANAX_LAST_USED` varchar(15) DEFAULT NULL,
  `OTHER_LAST_USED` varchar(15) DEFAULT NULL,
  `ALCOHOL_YEARS_USED` varchar(15) DEFAULT NULL,
  `COCAINE_YEARS_USED` varchar(15) DEFAULT NULL,
  `MARIJUANA_YEARS_USED` varchar(15) DEFAULT NULL,
  `OXYCODONE_YEARS_USED` varchar(15) DEFAULT NULL,
  `SPEED_YEARS_USED` varchar(15) DEFAULT NULL,
  `HEROIN_YEARS_USED` varchar(15) DEFAULT NULL,
  `XANAX_YEARS_USED` varchar(15) DEFAULT NULL,
  `OTHER_YEARS_USED` varchar(15) DEFAULT NULL,
  `SOBER_1_YEAR` varchar(15) DEFAULT NULL,
  `SOBER_3_YEARS` varchar(15) DEFAULT NULL,
  `USAGE_PATTERN` varchar(300) DEFAULT NULL,
  `QUANTITY_PER_WEEK` varchar(45) DEFAULT NULL,
  `QUANTITY_2_YEARS` varchar(45) DEFAULT NULL,
  `USAGE_LOSSES` varchar(300) DEFAULT NULL,
  `PHYSICAL_EFFECTS` varchar(300) DEFAULT NULL,
  `AA_FLAG` varchar(45) DEFAULT NULL,
  `NA_FLAG` varchar(45) DEFAULT NULL,
  `PREV_FF_FLAG` varchar(3) DEFAULT NULL,
  `PREV_FF_YEAR` varchar(45) DEFAULT NULL,
  `PREV_FF_OTHER` varchar(45) DEFAULT NULL,
  `CURRENT_HEALTH` varchar(45) DEFAULT NULL,
  `MEDICATION_FLAG` varchar(3) DEFAULT NULL,
  `MEDICATION_SUPPLY_FLAG` varchar(3) DEFAULT NULL,
  `MEDICATION_NEED_FLAG` varchar(3) DEFAULT NULL,
  `MEDICATION_DETAILS` varchar(45) DEFAULT NULL,
  `MEDICATION_REFILL_DETAILS` varchar(45) DEFAULT NULL,
  `DOCTOR_APPT_FLAG` varchar(3) DEFAULT NULL,
  `DOCTOR_APPT_DETAILS` varchar(45) DEFAULT NULL,
  `EYEWEAR_FLAG` varchar(3) DEFAULT NULL,
  `EYEWEAR_USAGE` varchar(45) DEFAULT NULL,
  `HOMELESS_TIME` varchar(300) DEFAULT NULL,
  `HOMELESS_REASON` varchar(300) DEFAULT NULL,
  `HOMELESS_HOW_OFTEN` varchar(300) DEFAULT NULL,
  `INDUSTRIAL_INJURY_FLAG` varchar(3) DEFAULT NULL,
  `INDUSTRIAL_INJURY_DATE` varchar(45) DEFAULT NULL,
  `INDUSTRIAL_INJURY_REASON` varchar(45) DEFAULT NULL,
  `INDUSTRIAL_INJURY_LOCATION` varchar(45) DEFAULT NULL,
  `INDUSTRIAL_INJURY_EMPLOYER` varchar(45) DEFAULT NULL,
  `INDUSTRIAL_INJURY_CLAIM_STATUS` varchar(45) DEFAULT NULL,
  `DISABILITY_FLAG` varchar(3) DEFAULT NULL,
  `DISABILITY_DETAILS` varchar(45) DEFAULT NULL,
  `DISABILITY_EXAMINATION_DATE` varchar(45) DEFAULT NULL,
  `DISABILITY_PHYSICIAN` varchar(45) DEFAULT NULL,
  `DISABILITY_PHYSICIAN_ADDRESS` varchar(45) DEFAULT NULL,
  `HERNIA_SIDE` varchar(45) DEFAULT NULL,
  `HERNIA_OPERATION_FLAG` varchar(3) DEFAULT NULL,
  `HERNIA_DETAILS` varchar(45) DEFAULT NULL,
  `LAWSUIT_FLAG` varchar(45) DEFAULT NULL,
  `CURRENT_LAWSUIT_FLAG` varchar(3) DEFAULT NULL,
  `LAWSUIT_DETAILS` mediumtext CHARACTER SET latin1,
  `CURRENT_LAWSUIT_DETAILS` mediumtext CHARACTER SET latin1,
  `FELONY_FLAG` varchar(45) DEFAULT NULL,
  `SEXUAL_OFFENSE_FLAG` varchar(3) DEFAULT NULL,
  `FELONY_DETAILS` mediumtext CHARACTER SET latin1,
  `SEXUAL_OFFENSE_QTY` varchar(2) DEFAULT NULL,
  `SEXUAL_OFFENSE_DETAILS` mediumtext CHARACTER SET latin1,
  `PROBATION_FLAG` varchar(3) DEFAULT NULL,
  `PROBATION_COUNTY` varchar(45) DEFAULT NULL,
  `PROBATION_OFFICER` varchar(45) DEFAULT NULL,
  `PROBATION_OFFICER_PHONE` varchar(45) DEFAULT NULL,
  `PROBATION_APPT_FLAG` varchar(3) DEFAULT NULL,
  `PROBATION_APPT_DETAILS` mediumtext CHARACTER SET latin1,
  `INCOME_AMOUNT` varchar(45) DEFAULT NULL,
  `INCOME_SOURCE` varchar(45) DEFAULT NULL,
  `INCOME_WEEKLY_FLAG` varchar(3) DEFAULT NULL,
  `INCOME_MONTHLY_FLAG` varchar(3) DEFAULT NULL,
  `APPLICATION_STATUS` varchar(80) DEFAULT NULL,
  `APPLICATION_SIGNATURE` varchar(45) DEFAULT NULL,
  `INTAKE_COUNSELOR_SIGNATURE` varchar(45) DEFAULT NULL,
  `DIRECTOR_SIGNATURE` varchar(45) DEFAULT NULL,
  `APPLICATION_SIGN_DATE` varchar(45) DEFAULT NULL,
  `INTAKE_COUNSELOR_SIGN_DATE` varchar(45) DEFAULT NULL,
  `DIRECTOR_SIGN_DATE` varchar(45) DEFAULT NULL,
  `CELL_DISCLOSURE_CONSENT` varchar(45) DEFAULT NULL,
  `RELEASE_WAIVER_CONSENT` varchar(45) DEFAULT NULL,
  `BIBLICAL_COUNSELING_CONSENT` varchar(45) DEFAULT NULL,
  `ENTRY_AGREEMENT_CONSENT` varchar(45) DEFAULT NULL,
  `RULES_VISITATION_CONSENT` varchar(45) DEFAULT NULL,
  `RELEASE_INFORMATION_CONSENT` varchar(45) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(45) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(45) DEFAULT NULL,
  `SUBMISSION_DATE` varchar(45) DEFAULT NULL,
  `ENTRY_DATE` varchar(45) DEFAULT NULL,
  `INTAKE_STATUS` varchar(80) DEFAULT 'In Program',
  `IMAGE_HEADSHOT` mediumblob,
  `IMAGE_STATE_ID` blob,
  `IMAGE_SSN` blob,
  `PROBATION_STATE` varchar(45) DEFAULT NULL,
  `RELATIONSHIP_WITH_MOTHER` varchar(45) DEFAULT NULL,
  `RELATIONSHIP_WITH_FATHER` varchar(45) DEFAULT NULL,
  `MEDICAL_CONDITION_DETAILS` varchar(60) DEFAULT NULL,
  `HERNIA_DATE` varchar(45) DEFAULT NULL,
  `OTHER_JOB_SKILL` varchar(45) DEFAULT NULL,
  `FARM_BASE` varchar(45) DEFAULT NULL,
  `EXIT_DATE` varchar(45) DEFAULT NULL,
  `SUPERVISOR` varchar(45) DEFAULT NULL,
  `JOB` varchar(45) DEFAULT NULL,
  `CLASS` varchar(45) DEFAULT NULL,
  `AREA` varchar(45) DEFAULT NULL,
  `ROOM` varchar(45) DEFAULT NULL,
  `BED` varchar(45) DEFAULT NULL,
  `ARCHIVED_FLAG` varchar(3) DEFAULT NULL,
  `DEPARTMENT_ID` bigint(20) DEFAULT NULL,
  `SUPERVISOR_ID` bigint(20) DEFAULT NULL,
  `JOB_ID` bigint(20) DEFAULT NULL,
  `other_benefits` varchar(100) DEFAULT NULL,
  `aa_years` varchar(20) DEFAULT NULL,
  `LAWSUIT_DATE` varchar(20) DEFAULT NULL,
  `CURRENT_LAWSUIT_DATE` varchar(20) DEFAULT NULL,
  `FELONY_QTY` int(11) DEFAULT NULL,
  `NEED_MEDICATION_FLAG` varchar(45) DEFAULT NULL,
  `EMPLOYER1_NAME` varchar(60) DEFAULT NULL,
  `EMPLOYER2_NAME` varchar(60) DEFAULT NULL,
  `EMPLOYER3_NAME` varchar(60) DEFAULT NULL,
  `EMPLOYER1_DATES` varchar(20) DEFAULT NULL,
  `EMPLOYER2_DATES` varchar(20) DEFAULT NULL,
  `EMPLOYER3_DATES` varchar(20) DEFAULT NULL,
  `EMPLOYER4_DATES` varchar(20) DEFAULT NULL,
  `EMPLOYER1_CONTACT` varchar(60) DEFAULT NULL,
  `EMPLOYER2_CONTACT` varchar(60) DEFAULT NULL,
  `EMPLOYER3_CONTACT` varchar(2060) DEFAULT NULL,
  `EMPLOYER4_CONTACT` varchar(60) DEFAULT NULL,
  `EMPLOYER1_PHONE` varchar(20) DEFAULT NULL,
  `EMPLOYER2_PHONE` varchar(20) DEFAULT NULL,
  `EMPLOYER3_PHONE` varchar(20) DEFAULT NULL,
  `EMPLOYER4_PHONE` varchar(20) DEFAULT NULL,
  `EMPLOYER1_JOB` varchar(60) DEFAULT NULL,
  `EMPLOYER2_JOB` varchar(60) DEFAULT NULL,
  `EMPLOYER3_JOB` varchar(60) DEFAULT NULL,
  `EMPLOYER4_JOB` varchar(60) DEFAULT NULL,
  `EMPLOYER4_NAME` varchar(60) DEFAULT NULL,
  `SS_FLAG` varchar(20) DEFAULT NULL,
  `VA_FLAG` varchar(20) DEFAULT NULL,
  `WC_FLAG` varchar(20) DEFAULT NULL,
  `NEED_GED` varchar(20) DEFAULT NULL,
  `SPIRITUAL_EXPERIENCE` varchar(80) DEFAULT NULL,
  `FOOD_STAMP_FLAG` varchar(20) DEFAULT NULL,
  `CASE_NOTES` mediumtext CHARACTER SET latin1,
  `RESPONSE_STATUS` varchar(60) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(80) DEFAULT NULL,
  `APPLICATION_SUBMISSION_DATE` varchar(20) DEFAULT NULL,
  `STATE_ID_TYPE` varchar(100) DEFAULT NULL,
  `REAPPLY_FLAG` varchar(20) DEFAULT NULL,
  `GENDER` varchar(20) DEFAULT NULL,
  `CWT_PROGRAM_ID` bigint(20) DEFAULT NULL,
  `ARRIVAL_DATE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4117024 DEFAULT CHARSET=utf8;

CREATE TABLE `intake_course_enrollment` (
  `INTAKE_COURSE_ENROLLMENT_ID` bigint(20) NOT NULL,
  `COURSE_ID` bigint(20) NOT NULL,
  `INTAKE_ID` bigint(20) NOT NULL,
  `STATUS` varchar(15) NOT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_COURSE_ENROLLMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='			';

CREATE TABLE `intake_employer` (
  `INTAKE_EMPLOYER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(45) NOT NULL,
  `CONTACT_NAME` varchar(45) NOT NULL,
  `CONTACT_PHONE` varchar(45) NOT NULL,
  `BEGIN_DATE` varchar(45) NOT NULL,
  `END_DATE` varchar(45) DEFAULT NULL,
  `INTAKE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`INTAKE_EMPLOYER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `intake_job_assignment` (
  `INTAKE_JOB_ASSIGNMENT_ID` bigint(20) NOT NULL,
  `JOB_ASSIGNMENT_ID` bigint(20) NOT NULL,
  `INTAKE_ID` bigint(20) NOT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_JOB_ASSIGNMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `intake_job_history` (
  `INTAKE_JOB_HISTORY_ID` bigint(20) NOT NULL,
  `JOB_ASSIGNMENT_ID` bigint(20) NOT NULL,
  `INTAKE_ID` bigint(20) NOT NULL,
  `BEGIN_DATE` varchar(10) NOT NULL,
  `END_DATE` varchar(10) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_JOB_HISTORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `intake_job_skill` (
  `JOB_SKILL_ID` bigint(20) NOT NULL,
  `INTAKE_ID` bigint(45) DEFAULT NULL,
  `intake_job_skill_id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`intake_job_skill_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4186 DEFAULT CHARSET=utf8;

CREATE TABLE `intake_medical_condition` (
  `INTAKE_MEDICAL_CONDITION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INTAKE_ID` bigint(20) NOT NULL,
  `ANSWER` varchar(3) NOT NULL DEFAULT 'NO',
  `MEDICAL_CONDITION_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_MEDICAL_CONDITION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=806 DEFAULT CHARSET=utf8;

CREATE TABLE `intake_question_answer` (
  `INTAKE_QUESTION_ANSWER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `QUESTION_ID` bigint(20) NOT NULL,
  `ANSWER` varchar(3) DEFAULT 'NO',
  `INTAKE_ID` bigint(20) NOT NULL,
  `DETAIL` varchar(65) DEFAULT NULL,
  `DATES` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_QUESTION_ANSWER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=21788 DEFAULT CHARSET=utf8;

CREATE TABLE `intake_record_entry` (
  `INTAKE_RECORD_ENTRY_ID` int(11) NOT NULL,
  `INTAKE_ID` bigint(20) NOT NULL,
  `RECORD_TYPE` varchar(25) DEFAULT NULL,
  `DESCRIPTION` longtext,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_RECORD_ENTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `intake_reference` (
  `INTAKE_REFERENCE` bigint(20) NOT NULL AUTO_INCREMENT,
  `INTAKE_ID` bigint(20) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `CONTACT_PHONE` varchar(45) DEFAULT NULL,
  `CONTACT_EMAIL` varchar(45) DEFAULT NULL,
  `YEARS_KNOWN` varchar(45) DEFAULT NULL,
  `RELATIONSHIP` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INTAKE_REFERENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ip_permission` (
  `ip_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(20) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ip_id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

CREATE TABLE `job_skill` (
  `JOB_SKILL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(45) NOT NULL,
  PRIMARY KEY (`JOB_SKILL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

CREATE TABLE `job_supervisor` (
  `JOB_SUPERVISOR_ID` bigint(20) NOT NULL,
  `LASTNAME` varchar(30) DEFAULT NULL,
  `FIRSTNAME` varchar(30) DEFAULT NULL,
  `JOB_ASSIGNMENT_ID` varchar(45) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`JOB_SUPERVISOR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `jobskill_csv` (
  `personKey` int(10) DEFAULT NULL,
  `truckDriver` varchar(255) DEFAULT NULL,
  `otherSkill` varchar(255) DEFAULT NULL,
  `electrician` varchar(255) DEFAULT NULL,
  `employer4` varchar(255) DEFAULT NULL,
  `employer1` varchar(255) DEFAULT NULL,
  `employer2` varchar(255) DEFAULT NULL,
  `employer3` varchar(255) DEFAULT NULL,
  `officeWork` varchar(255) DEFAULT NULL,
  `contactNumber3` varchar(255) DEFAULT NULL,
  `contactNumber2` varchar(255) DEFAULT NULL,
  `contactNumber1` varchar(255) DEFAULT NULL,
  `contactNumber4` varchar(255) DEFAULT NULL,
  `contactName3` varchar(255) DEFAULT NULL,
  `contactName2` varchar(255) DEFAULT NULL,
  `contactName1` varchar(255) DEFAULT NULL,
  `forkLiftOperator` varchar(255) DEFAULT NULL,
  `radioTvRepair` varchar(255) DEFAULT NULL,
  `contactName4` varchar(255) DEFAULT NULL,
  `computerProgramming` varchar(255) DEFAULT NULL,
  `maintenance` varchar(255) DEFAULT NULL,
  `jobTitle2` varchar(255) DEFAULT NULL,
  `jobTitle3` varchar(255) DEFAULT NULL,
  `airConditioning` varchar(255) DEFAULT NULL,
  `jobTitle1` varchar(255) DEFAULT NULL,
  `jobTitle4` varchar(255) DEFAULT NULL,
  `mechanic` varchar(255) DEFAULT NULL,
  `custodian` varchar(255) DEFAULT NULL,
  `carpenter` varchar(255) DEFAULT NULL,
  `sales` varchar(255) DEFAULT NULL,
  `beginDate3` varchar(255) DEFAULT NULL,
  `beginDate2` varchar(255) DEFAULT NULL,
  `beginDate1` varchar(255) DEFAULT NULL,
  `lastUpdatedBy` varchar(255) DEFAULT NULL,
  `key` int(10) DEFAULT NULL,
  `beginDate4` varchar(255) DEFAULT NULL,
  `cook` varchar(255) DEFAULT NULL,
  `painter` varchar(255) DEFAULT NULL,
  `kitchen` varchar(255) DEFAULT NULL,
  `plumber` varchar(255) DEFAULT NULL,
  `upholstery` varchar(255) DEFAULT NULL,
  `phoneRoom` varchar(255) DEFAULT NULL,
  `computerRepair` varchar(255) DEFAULT NULL,
  `landscaping` varchar(255) DEFAULT NULL,
  `autoBodyRepair` varchar(255) DEFAULT NULL,
  `warehousing` varchar(255) DEFAULT NULL,
  `applianceRepair` varchar(255) DEFAULT NULL,
  `endDate1` varchar(255) DEFAULT NULL,
  `endDate3` varchar(255) DEFAULT NULL,
  `endDate2` varchar(255) DEFAULT NULL,
  `endDate4` varchar(255) DEFAULT NULL,
  `lastUpdatedDate` varchar(255) DEFAULT NULL,
  `welder` varchar(255) DEFAULT NULL,
  `clothesSorter` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `medical_condition` (
  `MEDICAL_CONDITION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(45) NOT NULL,
  `sequence` int(11) DEFAULT NULL,
  PRIMARY KEY (`MEDICAL_CONDITION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

CREATE TABLE `person_csv` (
  `lastPersonStatus` varchar(255) DEFAULT NULL,
  `emergencyPhone` varchar(255) DEFAULT NULL,
  `exitDate` varchar(255) DEFAULT NULL,
  `englishReadFlag` varchar(255) DEFAULT NULL,
  `referredBy` varchar(255) DEFAULT NULL,
  `height` varchar(255) DEFAULT NULL,
  `englishSpeakFlag` varchar(255) DEFAULT NULL,
  `graduateFlag` varchar(255) DEFAULT NULL,
  `maritalStatus` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `workAssignment` varchar(255) DEFAULT NULL,
  `personStatus` varchar(255) DEFAULT NULL,
  `entryDate` varchar(255) DEFAULT NULL,
  `bedNumber` varchar(255) DEFAULT NULL,
  `saved` int(10) DEFAULT NULL,
  `ethnicity` varchar(255) DEFAULT NULL,
  `currentCourse` int(10) DEFAULT NULL,
  `ssn` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `ytdPaid` int(10) DEFAULT NULL,
  `emergencyContact` varchar(255) DEFAULT NULL,
  `synced` varchar(255) DEFAULT NULL,
  `dateOfBirth` timestamp NULL DEFAULT NULL,
  `lastStatusUpdated` varchar(255) DEFAULT NULL,
  `specialNotes` varchar(255) DEFAULT NULL,
  `supervisor` varchar(255) DEFAULT NULL,
  `homeLocation` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `cellPhone` varchar(255) DEFAULT NULL,
  `educationLevel` varchar(255) DEFAULT NULL,
  `referralPhone` varchar(255) DEFAULT NULL,
  `suffix` varchar(255) DEFAULT NULL,
  `eyeColor` varchar(255) DEFAULT NULL,
  `lastUpdatedBy` varchar(255) DEFAULT NULL,
  `legacyComment` varchar(255) DEFAULT NULL,
  `person_id` int(10) DEFAULT NULL,
  `organization` varchar(255) DEFAULT NULL,
  `hairColor` varchar(255) DEFAULT NULL,
  `workPhone` varchar(255) DEFAULT NULL,
  `creationDate` varchar(255) DEFAULT NULL,
  `homePhone` varchar(255) DEFAULT NULL,
  `emergencyRelationship` varchar(255) DEFAULT NULL,
  `firstName` varchar(255) DEFAULT NULL,
  `lastName` varchar(255) DEFAULT NULL,
  `age` int(10) DEFAULT NULL,
  `middleInitial` varchar(255) DEFAULT NULL,
  `personType` varchar(255) DEFAULT NULL,
  `farmBase` varchar(255) DEFAULT NULL,
  `imageKey` varchar(255) DEFAULT NULL,
  `lastUpdatedDate` varchar(255) DEFAULT NULL,
  `currentClass` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `personaddress$` (
  `building` varchar(255) DEFAULT NULL,
  `cellPhone` varchar(255) DEFAULT NULL,
  `structureType` varchar(255) DEFAULT NULL,
  `buildingNumber` varchar(255) DEFAULT NULL,
  `subdivision` varchar(255) DEFAULT NULL,
  `gateInstructions` varchar(255) DEFAULT NULL,
  `apartmentNumber` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `streetSuffix` varchar(255) DEFAULT NULL,
  `floorNumber` varchar(255) DEFAULT NULL,
  `zipcode` double DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `addressLine2` varchar(255) DEFAULT NULL,
  `workPhone` varchar(255) DEFAULT NULL,
  `addressLine1` varchar(255) DEFAULT NULL,
  `elevatorFlag` varchar(255) DEFAULT NULL,
  `majorIntersection` varchar(255) DEFAULT NULL,
  `personKey` double DEFAULT NULL,
  `homePhone` varchar(255) DEFAULT NULL,
  `gatedCommunity` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `question` (
  `QUESTION_ID` bigint(20) NOT NULL DEFAULT '0',
  `QUESTION` varchar(250) NOT NULL,
  `sequence` int(11) DEFAULT NULL,
  PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `state` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` char(40) NOT NULL,
  `value` char(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=utf8;

CREATE TABLE `student_discipline_history` (
  `student_discipline_history_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `intake_id` bigint(20) DEFAULT NULL,
  `violation_area` varchar(50) DEFAULT NULL,
  `violation_type` varchar(50) DEFAULT NULL,
  `violation_date` varchar(20) DEFAULT NULL,
  `warnings` varchar(20) DEFAULT NULL,
  `fines` varchar(20) DEFAULT NULL,
  `additional_consquences` varchar(20) DEFAULT NULL,
  `comments` mediumtext CHARACTER SET latin1,
  `created_by` varchar(40) DEFAULT NULL,
  `creation_date` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`student_discipline_history_id`)
) ENGINE=InnoDB AUTO_INCREMENT=111 DEFAULT CHARSET=utf8;

CREATE TABLE `student_history` (
  `STUDENT_HISTORY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `INTAKE_ID` bigint(20) NOT NULL,
  `PHASE` varchar(60) DEFAULT NULL,
  `PROGRAM_STATUS` varchar(60) DEFAULT NULL,
  `REASON` varchar(200) DEFAULT NULL,
  `BEGIN_DATE` varchar(30) DEFAULT NULL,
  `END_DATE` varchar(30) DEFAULT NULL,
  `CREATION_DATE` varchar(45) DEFAULT NULL,
  `CREATED_BY` varchar(45) DEFAULT NULL,
  `FARM` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`STUDENT_HISTORY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9810 DEFAULT CHARSET=utf8;

CREATE TABLE `student_pass_history` (
  `student_pass_history_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `intake_id` bigint(20) DEFAULT NULL,
  `hours` varchar(45) DEFAULT NULL,
  `pass_date` varchar(45) DEFAULT NULL,
  `pass_type` varchar(45) DEFAULT NULL,
  `creation_date` varchar(45) DEFAULT NULL,
  `created_by` varchar(45) DEFAULT NULL,
  `comments` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`student_pass_history_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1084 DEFAULT CHARSET=utf8;

CREATE TABLE `system_user` (
  `USER_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(15) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL,
  `CREATION_DATE` varchar(30) DEFAULT NULL,
  `LAST_UPDATED_DATE` varchar(30) DEFAULT NULL,
  `USER_ROLE` varchar(40) NOT NULL,
  `FARM_BASE` varchar(25) DEFAULT NULL,
  `LOGIN_COUNT` bigint(20) DEFAULT '0',
  `CREATED_BY` varchar(25) DEFAULT NULL,
  `QUESTION` varchar(45) DEFAULT NULL,
  `ANSWER` varchar(45) DEFAULT NULL,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(20) DEFAULT NULL,
  `LAST_UPDATED_BY` varchar(20) DEFAULT NULL,
  `GROUP_` varchar(20) DEFAULT NULL,
  `INSTRUCTOR_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10082 DEFAULT CHARSET=utf8;

CREATE TABLE `user_authorized_session` (
  `SESSION_ID` varchar(100) NOT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `LOGIN_TIME` varchar(20) DEFAULT NULL,
  `ACTIVE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

